Fix issue with jquery init
jonasundderwolf/django-admin-locking pull request #5
Opened 2021-10-22 07:34 UTC by jhrdt

Fix for issue #4.

The main cause of the malfunction is a missing jQuery init and a removed function (unload()) from jQuery 3.

2021-10-22 08:53 UTC, MRigal requested changes

2021-10-22 08:53 UTC, MRigal commented on admin_locking/static/admin_locking/admin_locking.js
>      $(window).unload(clear_lock);
Isn't the try/catch block aimed to replace this line?

2021-10-22 09:30 UTC, jhrdt commented on admin_locking/static/admin_locking/admin_locking.js
>      $(window).unload(clear_lock);
Fixed it.

2021-10-22 09:48 UTC, MRigal commented on admin_locking/admin.py
> +            'admin_locking/admin_locking.js',
Have you tried this version yourself? With Django 3.2, I get the following `jQuery is not a function`, issued from some code coming from jquery.init.js. One option is to add also jquery here, but this starts to be really noisy for a small JS function.

From what I've seen on the net, the best might be actually to drop any jquery reference here, but ensure it is wrapped to be executed only after jquery is loaded, as in https://stackoverflow.com/a/59057562/1504046

2021-10-22 09:48 UTC, MRigal commented on admin_locking/static/admin_locking/admin_locking.js
>      $(window).unload(clear_lock);
Thanks!

2021-10-22 10:12 UTC, jhrdt commented on admin_locking/admin.py
> +            'admin_locking/admin_locking.js',
My test setup has no issue.

```
$ pip freeze
Django==3.2.8
django-admin-locking==0.8.3
```

```
$ python3 -V
Python 3.8.10
```

2021-10-26 06:52 UTC, jhrdt commented on admin_locking/admin.py
> +            'admin_locking/admin_locking.js',
Hej @MRigal,

could you give more details on your setup? System & Browser? I would like to reproduce your error message. Does it occur while running in debug mode?

2021-10-27 07:24 UTC, jhrdt commented on admin_locking/admin.py
> +            'admin_locking/admin_locking.js',
Hi @MRigal, I added the suggest change. Please check 0eb8d0d.

2021-11-03 11:18 UTC, MRigal commented on admin_locking/admin.py
> +            'admin_locking/admin_locking.js',
Hi @jhrdt works like a charm now, Thanks a lot!

2021-11-03 11:20 UTC, MRigal approved these changes
Looks great, thanks for the fix! Would you like to add yourself to the CONTRIBUTOR file? Else I may just merge the PR and release a new version right after

2021-11-04 09:29 UTC, jhrdt commented
Hi @MRigal,

you can do the merge right away.

2021-11-04 16:22 UTC, merged

2021-11-04 16:42 UTC, MRigal commented
v0.9.0 was uploaded to PyPI. Thanks again!